services:
  kafka:
    image: apache/kafka:4.3.1
    container_name: nodejs-microservices-kafka
    ports:
      - "9092:9092"
    environment:
      # --- MAP INTERNAL DATA TRANSFERS ---
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLATFORM'
      # --- NETWORK LISTENERS ---
      KAFKA_ADVERTISED_LISTENERS: 'PLATFORM://localhost:9092'
      KAFKA_LISTENERS: 'PLATFORM://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLATFORM:PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      # --- AUTO-CREATE TOPICS ON THE FLY ---
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      # --- KRAFT SETUP ---
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@localhost:9093'
      # --- DEV REPLICATION ENVIRONMENT SETTINGS ---
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1